# fly.toml app configuration file generated for another-machines on 2023-06-07T16:08:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "another-machines"
primary_region = "gru"

